####
# This Dockerfile is used to build a container that runs the Quarkus application in JVM mode.
#
# Before building the container image, build the application:
#
# mvn package
#
# Then build the image:
#
# docker build -f src/main/docker/Dockerfile.jvm -t puma-skg-if-api-jvm .
#
# Then run the container:
#
# docker run -i --rm -p 8080:8080 puma-skg-if-api-jvm
#
###
FROM registry.access.redhat.com/ubi9/openjdk-21:1.21

ENV LANGUAGE='en_US:en'

# Four distinct layers so unchanged library/runtime layers can be cached separately
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
